<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Transfer extends Model
{
    protected $fillable = [
        'date',
        'from_account_type',
        'from_account_id',
        'to_account_type',
        'to_account_id',
        'amount',
        'description',
        'reference_no',
    ];

    protected $casts = [
        'amount' => 'decimal:2',
        'date'   => 'date',
    ];

    // ─── Lifecycle ────────────────────────────────────────────────────────────

    /**
     * Auto-generate a reference number before creation if not supplied.
     * Format: TRF-YYYYMMDD-XXXX  e.g. TRF-20260324-A3F7
     */
    protected static function booted(): void
    {
        static::creating(function (Transfer $transfer) {
            if (empty($transfer->reference_no)) {
                $transfer->reference_no = 'TRF-' . now()->format('Ymd') . '-' . strtoupper(Str::random(4));
            }
        });
    }

    // ─── Relationships ────────────────────────────────────────────────────────

    /**
     * All ledger_entries generated by this transfer (always 2 rows).
     */
    public function ledgerEntries()
    {
        return $this->hasMany(LedgerEntry::class, 'reference_id')
                    ->where('reference_type', 'Transfer');
    }

    /**
     * Resolve the source account (Client or Account model).
     */
    public function fromAccount()
    {
        if (in_array($this->from_account_type, ['customer', 'supplier'])) {
            return $this->belongsTo(Client::class, 'from_account_id');
        }

        return $this->belongsTo(Account::class, 'from_account_id');
    }

    /**
     * Resolve the destination account (Client or Account model).
     */
    public function toAccount()
    {
        if (in_array($this->to_account_type, ['customer', 'supplier'])) {
            return $this->belongsTo(Client::class, 'to_account_id');
        }

        return $this->belongsTo(Account::class, 'to_account_id');
    }

    // ─── Scopes ───────────────────────────────────────────────────────────────

    public function scopeInDateRange($query, ?string $from, ?string $to)
    {
        if ($from) {
            $query->where('date', '>=', $from);
        }
        if ($to) {
            $query->where('date', '<=', $to);
        }

        return $query;
    }

    public function scopeForAccountType($query, string $type)
    {
        return $query->where('from_account_type', $type)
                     ->orWhere('to_account_type', $type);
    }

    // ─── Helpers ──────────────────────────────────────────────────────────────

    /**
     * Human-readable label for this transfer's direction.
     * e.g. "Bank → Supplier"
     */
    public function getDirectionLabel(): string
    {
        $labels = [
            'customer' => 'Customer',
            'supplier' => 'Supplier',
            'bank'     => 'Bank',
            'cash'     => 'Cash',
        ];

        $from = $labels[$this->from_account_type] ?? $this->from_account_type;
        $to   = $labels[$this->to_account_type]   ?? $this->to_account_type;

        return "{$from} → {$to}";
    }
}
